-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS YEAR_TABLE
(
    YEAR integer,
    PRIMARY KEY (YEAR)
);

CREATE TABLE IF NOT EXISTS CRIME_DATA
(
    UNI_ID integer,
    CRIME_YEAR integer,
    C_GUID character varying(15),
    VIO_UNI_ID integer,
    STATS_UNI_ID integer,
    UOM character varying(10),
    SCALAR_FACTOR character varying(8),
    VALUE integer,
    DECIMALS integer,
    PRIMARY KEY (UNI_ID)
);

CREATE TABLE IF NOT EXISTS IMMIGRATION
(
    IMM_ID integer,
    IMM_YEAR integer,
    IMM_MONTH character varying(10),
    PROVINCE character varying(10),
    P_GUID character varying(12),
    RESIDENT_TYPE character varying(50),
    UOM character varying(10),
    VALUE numeric,
    PRIMARY KEY (IMM_ID)
);

CREATE TABLE IF NOT EXISTS CRIME_SCENE
(
    GEO_ID integer,
    C_GUID character varying(15),
    CITY character varying(30),
    CRIME_ID integer,
    PRIMARY KEY (GEO_ID)
);

CREATE TABLE IF NOT EXISTS VIOLATIONS
(
    VIO_UNI_ID integer,
    VIOLATIONS character varying(50),
    CRIME_ID integer,
    PRIMARY KEY (VIO_UNI_ID)
);

CREATE TABLE IF NOT EXISTS STATISTICS
(
    STATS_UNI_ID integer,
    STATISTICS character varying(80),
    CRIME_ID integer,
    PRIMARY KEY (STATS_UNI_ID)
);

ALTER TABLE IF EXISTS CRIME_DATA
    ADD FOREIGN KEY (CRIME_YEAR)
    REFERENCES YEAR_TABLE (YEAR) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS IMMIGRATION
    ADD FOREIGN KEY (IMM_YEAR)
    REFERENCES YEAR_TABLE (YEAR) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
	

ALTER TABLE IF EXISTS CRIME_SCENE
    ADD FOREIGN KEY (CRIME_ID)
    REFERENCES CRIME_DATA (UNI_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS VIOLATIONS
    ADD FOREIGN KEY (CRIME_ID)
    REFERENCES CRIME_DATA (UNI_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS STATISTICS
    ADD FOREIGN KEY (CRIME_ID)
    REFERENCES CRIME_DATA (UNI_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;